### ISSUE TITLE
连接时无法弹出PIN密码输入框

### ISSUE THREAD

**Issue by Vanish136** [dingjikerbo/Android-BluetoothKit#135]
硬件蓝牙设备连接要求输入指定的密码，用该框架调用连接方法.connect()后，手机上没有弹出密码输入框，然后就连接失败了。请问有人知道怎么做吗？？？？

**Comment by zuoni1018** [comment]
notify 一下会弹出来的

**Comment by Vanish136** [comment]
谢谢，我是搞错了 我这里硬件设备是SPP协议的经典蓝牙，不能用BLE模式连接，需要自己写连接和通讯
